# model
model_name_or_path: saves/llama3-70B/pretrain_v2
quantization_bit: 4

# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# ddp
ddp_timeout: 180000000

# dataset
dataset: sm_question, identity, founq
template: llama3
cutoff_len: 1024
max_samples: 100000
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: saves/llama3-70B/lora/sft_v2
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
push_to_hub: true
hub_model_id: ytcheng/llama3-70B-lora-sft_v2

# train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 100
